# Animales de Olivia: clave, nombre con articulo, categoria, nombre cientifico (iNaturalist),
# grabaciones elegidas a mano en Wikimedia Commons y clases de sonido esperadas (YAMNet).
A = [
('perro','el perro','casa','Canis familiaris',['Barking of a dog 2.ogg','Perro ladrando.ogg','Barking of a dog.ogg'],[69,70,73]),
('gato','el gato','casa','Felis catus',['Meow of a pleading cat.oga','Felis silvestris catus meows.ogg','Meow domestic cat.ogg'],[76,78]),
('vaca','la vaca','granja','Bos taurus',['Single Cow Moo.ogg','Mudchute cow 1.ogg','Cow in Antefasy.wav'],[85,86]),
('oveja','la oveja','granja','Ovis aries',['Sheep bleating.ogg',"Lamb bleating and its mother's response.flac"],[91,92]),
('cabra','la cabra','granja','Capra hircus',['Herd of goats bleating.ogg'],[90,91]),
('cerdo','el cerdo','granja','Sus scrofa domesticus',['Pig grunt - Erdie.ogg'],[88,89]),
('caballo','el caballo','granja','Equus caballus',['Wiehern.ogg','Mares-Prefer-the-Voices-of-Highly-Fertile-Stallions-pone.0118468.s003.oga'],[82,84]),
('burro','el burro','granja','Equus asinus',['157763 felix-blume a-donkey-is-braying-in-his-enclosure-in-south-of-france.wav'],[82,84,67]),
('gallina','la gallina','granja','Gallus gallus domesticus',['Hen announcing shes lain an egg.ogg','Hens leaving coop.ogg'],[95]),
('gallo','el gallo','granja','Gallus gallus domesticus',['Rooster crowing.oga','Medium rooster crowing.ogg','Rooster crowing.ogg'],[96]),
('pato','el pato','granja','Anas platyrhynchos',['Pekin duck & mallard.ogg'],[99,100]),
('pavo','el pavo','granja','Meleagris gallopavo',[],[97,98]),
('ganso','el ganso','granja','Anser anser',[],[101,102]),
('pavoreal','el pavo real','granja','Pavo cristatus',['MalePeacockCall.ogg','Indian Peafowl.ogg'],[106,107,109]),
('leon','el león','selva','Panthera leo',[],[104,105]),
('tigre','el tigre','selva','Panthera tigris',[],[104,105]),
('elefante','el elefante','selva','Loxodonta africana',['Elephant voice - trumpeting.ogg'],[67,103]),
('gorila','el gorila','selva','Gorilla gorilla',[],[67,103]),
('chimpance','el chimpancé','selva','Pan troglodytes',[],[67,103]),
('monoaullador','el mono aullador','selva','Alouatta palliata',[],[67,103,105]),
('cebra','la cebra','selva','Equus quagga',[],[82,84,67]),
('hipopotamo','el hipopótamo','selva','Hippopotamus amphibius',[],[67,103]),
('hiena','la hiena','selva','Crocuta crocuta',['Spotted Hyena Grunting (Crocuta crocuta).ogg'],[67,103]),
('loro','el loro','selva','Ara macao',[],[106,109]),
('tucan','el tucán','selva','Ramphastos sulfuratus',[],[106,107]),
('caiman','el caimán','selva','Alligator mississippiensis',[],[67,103,105]),
('leopardo','el leopardo','selva','Panthera pardus',[],[104,105]),
('jaguar','el jaguar','selva','Panthera onca',[],[104,105]),
('rinoceronte','el rinoceronte','selva','Ceratotherium simum',[],[67,103]),
('suricata','la suricata','selva','Suricata suricatta',[],[67,103]),
('lobo','el lobo','bosque','Canis lupus',['Wolf howls.ogg'],[72,117]),
('oso','el oso','bosque','Ursus arctos',[],[74,103,105]),
('zorro','el zorro','bosque','Vulpes vulpes',[],[117,67,70]),
('ciervo','el ciervo','bosque','Cervus elaphus',[],[67,103,105]),
('jabali','el jabalí','bosque','Sus scrofa',[],[88,89,67]),
('buho','el búho','bosque','Bubo bubo',[],[114,115]),
('carpintero','el pájaro carpintero','bosque','Picus sharpei',[],[106,107]),
('cuco','el cuco','bosque','Cuculus canorus',[],[106,107,110]),
('ardilla','la ardilla','bosque','Sciurus vulgaris',[],[106,67,118]),
('rana','la rana','bosque','Pelophylax perezi',[],[127,128]),
('grillo','el grillo','bosque','Gryllus campestris',[],[121,122]),
('cigarra','la cigarra','bosque','Lyristes plebejus',[],[121,122]),
('abeja','la abeja','bosque','Apis mellifera',[],[125,126]),
('koala','el koala','bosque','Phascolarctos cinereus',[],[67,103,74]),
('ballena','la ballena','mar','Megaptera novaeangliae',[],[131]),
('delfin','el delfín','mar','Delphinus delphis',[],[131,67]),
('leonmarino','el león marino','mar','Zalophus californianus',[],[67,70,103]),
('pinguino','el pingüino','mar','Spheniscus demersus',[],[67,106,109]),
('gaviota','la gaviota','mar','Larus michahellis',[],[106,109]),
('nutria','la nutria','mar','Lutra lutra',[],[67,103]),
('gorrion','el gorrión','pajaros','Passer domesticus',[],[106,107,108]),
('petirrojo','el petirrojo','pajaros','Erithacus rubecula',[],[106,107,108]),
('mirlo','el mirlo','pajaros','Turdus merula',[],[106,107,108]),
('cuervo','el cuervo','pajaros','Corvus corax',[],[112,113]),
('paloma','la paloma','pajaros','Columba livia',[],[110,111]),
('canario','el canario','pajaros','Serinus canaria',[],[106,107,108]),
('ciguena','la cigüeña','pajaros','Ciconia ciconia',['Ciconia ciconia bill-clattering.ogg'],[67,106,130]),
('golondrina','la golondrina','pajaros','Hirundo rustica',[],[106,107,108]),
('aguila','el águila','pajaros','Aquila chrysaetos',[],[106,107]),
('flamenco','el flamenco','pajaros','Phoenicopterus roseus',[],[106,109]),
('cucaburra','el cucaburra','pajaros','Dacelo novaeguineae',[],[106,107]),
]
# Animales domesticos o de zoo: se aceptan grabaciones aunque iNaturalist no las marque como silvestres.
DOM = {'perro','gato','vaca','oveja','cabra','cerdo','caballo','burro','gallina','gallo','pato','pavo','ganso','pavoreal','canario','paloma','rinoceronte','suricata','koala','nutria'}
