# Animales de Olivia: clave, nombre con articulo, grupo biologico, nombre cientifico (iNaturalist),
# grabaciones elegidas a mano en Wikimedia Commons y clases de sonido esperadas (YAMNet).
A = [
('perro','el perro','mamiferos','Canis familiaris',['Barking of a dog 2.ogg','Perro ladrando.ogg','Barking of a dog.ogg'],[69,70,73]),
('gato','el gato','mamiferos','Felis catus',['Meow of a pleading cat.oga','Felis silvestris catus meows.ogg','Meow domestic cat.ogg'],[76,78]),
('vaca','la vaca','mamiferos','Bos taurus',['Single Cow Moo.ogg','Mudchute cow 1.ogg','Cow in Antefasy.wav'],[85,86]),
('oveja','la oveja','mamiferos','Ovis aries',['Sheep bleating.ogg',"Lamb bleating and its mother's response.flac"],[91,92]),
('cabra','la cabra','mamiferos','Capra hircus',['Herd of goats bleating.ogg'],[90,91]),
('cerdo','el cerdo','mamiferos','Sus scrofa domesticus',['Pig grunt - Erdie.ogg'],[88,89]),
('caballo','el caballo','mamiferos','Equus caballus',['Wiehern.ogg','Mares-Prefer-the-Voices-of-Highly-Fertile-Stallions-pone.0118468.s003.oga'],[82,84]),
('burro','el burro','mamiferos','Equus asinus',['157763 felix-blume a-donkey-is-braying-in-his-enclosure-in-south-of-france.wav'],[82,84,67]),
('gallina','la gallina','aves','Gallus gallus domesticus',['Hen announcing shes lain an egg.ogg','Hens leaving coop.ogg'],[95]),
('gallo','el gallo','aves','Gallus gallus domesticus',['Rooster crowing.oga','Medium rooster crowing.ogg','Rooster crowing.ogg'],[96]),
('pato','el pato','aves','Anas platyrhynchos',['Pekin duck & mallard.ogg'],[99,100]),
('pavo','el pavo','aves','Meleagris gallopavo',[],[97,98]),
('ganso','el ganso','aves','Anser anser',[],[101,102]),
('pavoreal','el pavo real','aves','Pavo cristatus',['MalePeacockCall.ogg','Indian Peafowl.ogg'],[106,107,109]),
('leon','el león','mamiferos','Panthera leo',[],[104,105]),
('tigre','el tigre','mamiferos','Panthera tigris',[],[104,105]),
('elefante','el elefante','mamiferos','Loxodonta africana',['Elephant voice - trumpeting.ogg'],[67,103]),
('gorila','el gorila','mamiferos','Gorilla gorilla',[],[67,103]),
('chimpance','el chimpancé','mamiferos','Pan troglodytes',[],[67,103]),
('monoaullador','el mono aullador','mamiferos','Alouatta palliata',[],[67,103,105]),
('cebra','la cebra','mamiferos','Equus quagga',[],[82,84,67]),
('hipopotamo','el hipopótamo','mamiferos','Hippopotamus amphibius',[],[67,103]),
('hiena','la hiena','mamiferos','Crocuta crocuta',['Spotted Hyena Grunting (Crocuta crocuta).ogg'],[67,103]),
('loro','el loro','aves','Ara macao',[],[106,109]),
('tucan','el tucán','aves','Ramphastos sulfuratus',[],[106,107]),
('caiman','el caimán','reptiles','Alligator mississippiensis',[],[67,103,105]),
('leopardo','el leopardo','mamiferos','Panthera pardus',[],[104,105]),
('jaguar','el jaguar','mamiferos','Panthera onca',[],[104,105]),
('rinoceronte','el rinoceronte','mamiferos','Ceratotherium simum',[],[67,103]),
('suricata','la suricata','mamiferos','Suricata suricatta',[],[67,103]),
('lobo','el lobo','mamiferos','Canis lupus',['Wolf howls.ogg'],[72,117]),
('oso','el oso','mamiferos','Ursus arctos',[],[74,103,105]),
('zorro','el zorro','mamiferos','Vulpes vulpes',[],[117,67,70]),
('ciervo','el ciervo','mamiferos','Cervus elaphus',[],[67,103,105]),
('jabali','el jabalí','mamiferos','Sus scrofa',[],[88,89,67]),
('buho','el búho','aves','Bubo bubo',[],[114,115]),
('carpintero','el pájaro carpintero','aves','Picus sharpei',[],[106,107]),
('cuco','el cuco','aves','Cuculus canorus',[],[106,107,110]),
('ardilla','la ardilla','mamiferos','Sciurus vulgaris',[],[106,67,118]),
('rana','la rana','anfibios','Pelophylax perezi',[],[127,128]),
('grillo','el grillo','insectos','Gryllus campestris',[],[121,122]),
('cigarra','la cigarra','insectos','Lyristes plebejus',[],[121,122]),
('abeja','la abeja','insectos','Apis mellifera',[],[125,126]),
('koala','el koala','mamiferos','Phascolarctos cinereus',[],[67,103,74]),
('ballena','la ballena','mamiferos','Megaptera novaeangliae',[],[131]),
('delfin','el delfín','mamiferos','Delphinus delphis',[],[131,67]),
('leonmarino','el león marino','mamiferos','Zalophus californianus',[],[67,70,103]),
('pinguino','el pingüino','aves','Spheniscus demersus',[],[67,106,109]),
('gaviota','la gaviota','aves','Larus michahellis',[],[106,109]),
('nutria','la nutria','mamiferos','Lutra lutra',[],[67,103]),
('gorrion','el gorrión','aves','Passer domesticus',[],[106,107,108]),
('petirrojo','el petirrojo','aves','Erithacus rubecula',[],[106,107,108]),
('mirlo','el mirlo','aves','Turdus merula',[],[106,107,108]),
('cuervo','el cuervo','aves','Corvus corax',[],[112,113]),
('paloma','la paloma','aves','Columba livia',[],[110,111]),
('canario','el canario','aves','Serinus canaria',[],[106,107,108]),
('ciguena','la cigüeña','aves','Ciconia ciconia',['Ciconia ciconia bill-clattering.ogg'],[67,106,130]),
('golondrina','la golondrina','aves','Hirundo rustica',[],[106,107,108]),
('aguila','el águila','aves','Aquila chrysaetos',[],[106,107]),
('flamenco','el flamenco','aves','Phoenicopterus roseus',[],[106,109]),
('cucaburra','el cucaburra','aves','Dacelo novaeguineae',[],[106,107]),
]
# Animales que conviven con personas o viven en centros: se aceptan sus grabaciones
# aunque iNaturalist no las marque como de vida silvestre.
DOM = {'perro','gato','vaca','oveja','cabra','cerdo','caballo','burro','gallina','gallo','pato','pavo','ganso','pavoreal','canario','paloma','rinoceronte','suricata','koala','nutria'}
